### ISSUE TITLE
Fails on make

### ISSUE THREAD

**Issue by JoviDeCroock** [kismetwireless/kismet#13]
my ./configure said everything was fine but when i'm compiling the newest version of this repository i get this error:

<img width="598" alt="screen shot 2017-10-25 at 20 10 02" src="https://user-images.githubusercontent.com/17125876/32015155-87ce42ae-b9c0-11e7-9cd7-5b1e30f21218.png">

This is on a raspberry Pi 3 but the wifi chip is patched with nexmon.

**Comment by kismetwireless** [comment]
Looks like you have a weird version of libmicrohttpd; what version are you trying to compile against?  0.9.30 is known to work.

**Comment by JoviDeCroock** [comment]
I have version 0.9.19

**Comment by kismetwireless** [comment]
It's possible you've still got an old copy of microhttpd kicking around, I can't replicate & haven't heard of this error happening before, unforuntately...

**Comment by JoviDeCroock** [comment]
I fixed it with:

```
cd
wget ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.30.tar.gz
tar zxvf libmicrohttpd-0.9.30.tar.gz
mv libmicrohttpd-0.9.30 libmicrohttpd
cd libmicrohttpd
./configure
make
make install
```

want me to make a PR to add this in the readme? :) 
Thanks for the quick responses btw, love your work

**Comment by kismetwireless** [comment]
I just rewrote that part of the code to avoid using quiesce entirely, now it disables throwing errors in the panic handler and just kills the mhd daemon.
That, hopefully, fixes it for any version.  I'm going to close this ticket for now but re-open it or toss a new one in if it doesn't seem to solve it!
